name: 'Size Compare'
description: 'Compare size of the built assets'
branding:
  icon: bar-chart-2
  color: blue
inputs:
  gist_id:
    description: Id of the GIST to save size to
    required: true
  gist_token:
    description: A personal access token with "gist" permission. Should be stored as a Secret.
    required: false
  github_token:
    description: A personal access token with "github" permission. Should be used standard token.
    required: true
  compare_against:
    description: Commit hash of the commit to compare against.
    required: false
  files:
    description: A glob pattern where to find bundle files compare size for
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
